name: aedenmurray.io

records:
  mx:
    - 1 aspmx.l.google.com.
    - 5 alt1.aspmx.l.google.com.
    - 5 alt2.aspmx.l.google.com.
    - 10 alt3.aspmx.l.google.com.
    - 10 alt4.aspmx.l.google.com.

  txt:
    - google-site-verification=EgEarN1EwJFq1MII54Bstz8YVjE5uswop8MaS9WlHIw